---
host_config:
# What is the local host IP of the host (this) computer
  host_ip: 192.168.1.101
  hostname: streamproxy1
  recieveport: 1935

stream_config:
  stream1:
    destinations:
      facebook_live:
        - primary_server:
          url: rtmp://facebooksucks.com/live/
          streamkey: stupidnumber
          resolution: 1080p50
          auth:
            username: imaperson
            password: thishsouldbenotbecleartext
        - backup_server:
          url: rtmp://facebooksucks.com/live/
          streamkey: stupidnumber
          resolution: 1080p50
          auth:
            username: imaperson
            password: thishsouldbenotbecleartext
  stream2:
    destinations:
      Vemeo_live:
        - primary_server:
          url: rtmp://vemeosucks.com/live/
          streamkey: stupidnumber
          resolution: 720p60
          auth:
            username: imaperson
            password: thishsouldbenotbecleartext
        - backup_server:
          url: rtmp://vemeosucks.com/live/
          streamkey: stupidnumber
          resolution: 720p30
          auth:
            username: imaperson
            password: thishsouldbenotbecleartext
